# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

version: '3'

vars: 
  CUR: '3.0.0'
  
tasks:
  setup: {silent:true}
 
  snap:
    ignore_error: true
    cmds:
    - |
      cd "nuvolaris-documentation/{{.CUR}}"
      git add *
      git commit -m "$(date +%D-%T)" -a
      git push origin "{{.CUR}}"

  preview:
  - task: build
  - cd docs ; python3 -m http.server

  build:
    desc: build the website
    ignore_error: true
    cmds:
    - task: snap
      vars:
        CUR: 3.0.0
    - npx antora --fetch --clean --attribute cur-ver="$(curl -s https://raw.githubusercontent.com/nuvolaris/olaris/0.3.0/nuvroot.json | jq .version -r)" antora-playbook.yml
    sources:
    - nuvolaris-documentation/3.0.0/**/*.adoc

  publish:
    desc: build the website on github
    cmds:
    - task: snap
      vars:
        CUR: 3.0.0
    - |
      TAG="v{{.CUR}}-beta.$(date +%y%m%d%H%M)"
      git tag -d $(git tag)
      git tag $TAG
      git commit -m $TAG -a
      git push origin main 
      git push origin --tags

